title: Hello, I'm Justine.
description: >
  Onlne educator in the digital arts.
permalink: ':title/'
# baseurl: "/educator"
# url: "https://justinenevans.github.io"
site-twitter:

# Author Settings
author: Justine Evans
author-img: justine-evans.svg
about-author: Graphics, Web, and Instructional Design
social-email: justine.n.evans@gmail.com
social-codepen: Media-Ed-Online
social-facebook:
social-github: media-ed-online
social-linkedin: justineevans
social-twitter:
social-vimeo: mediaedonline
social-website: justinenevans.com
social-youtube: channel/UCLQGKfv62jlWbsx_W_dZ3pQ

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: UA-75086195-6 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
include: ['_pages']
